name: custom_cached_image
description: A Flutter package for displaying cached network images with a shimmer loading effect.
version: 1.6.0
homepage: https://github.com/manushah77/custom_cached_image
repository: https://github.com/manushah77/custom_cached_image
documentation: https://pub.dev/documentation/custom_cached_image/latest/

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  # Assets section if you have any assets (e.g., images or GIFs) that your package requires.
  assets:
    - assets/upload.gif
    - assets/namePic.png
    - assets/simplePic.png

# Fonts section for any custom fonts, if needed.
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
